// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBITrJFb6hLeuKHpuUD1rszc0JRZkp_DJA',
    appId: '1:367497918343:web:23c3d6aa40107f909d4522',
    messagingSenderId: '367497918343',
    projectId: 'kitchen-bdy',
    authDomain: 'kitchen-bdy.firebaseapp.com',
    storageBucket: 'kitchen-bdy.firebasestorage.app',
    measurementId: 'G-BJES1M9Q66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAt_0CSa-JTOR_kQLC2AXpxTonil6DUkE',
    appId: '1:367497918343:android:5eecc5a7fd76f00f9d4522',
    messagingSenderId: '367497918343',
    projectId: 'kitchen-bdy',
    storageBucket: 'kitchen-bdy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh5aYvLzaMIkvkbscwWtxmC0DBrm5crk',
    appId: '1:367497918343:ios:608b89e694fb1d0a9d4522',
    messagingSenderId: '367497918343',
    projectId: 'kitchen-bdy',
    storageBucket: 'kitchen-bdy.firebasestorage.app',
    iosBundleId: 'com.example.kitchenBdy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh5aYvLzaMIkvkbscwWtxmC0DBrm5crk',
    appId: '1:367497918343:ios:608b89e694fb1d0a9d4522',
    messagingSenderId: '367497918343',
    projectId: 'kitchen-bdy',
    storageBucket: 'kitchen-bdy.firebasestorage.app',
    iosBundleId: 'com.example.kitchenBdy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBITrJFb6hLeuKHpuUD1rszc0JRZkp_DJA',
    appId: '1:367497918343:web:1b2d68bb08d45f3f9d4522',
    messagingSenderId: '367497918343',
    projectId: 'kitchen-bdy',
    authDomain: 'kitchen-bdy.firebaseapp.com',
    storageBucket: 'kitchen-bdy.firebasestorage.app',
    measurementId: 'G-P96RYC18HE',
  );

}